### ISSUE TITLE
Dictionary is overwritten entirely

### ISSUE THREAD

**Issue by pluggero** [pluggero/ansible-role-common-pkgs#15]
When I set this in a playbook for example:

```
common_pkgs:
      pacman:
        install:
          - ansible
```

The entire `common_pkgs` dictionary is overwritten.
Now, I need to initialize the complete `pacman` dictionary with all variables otherwise the role fails:

```
common_pkgs:
  pacman:
    install:
          - ansible
    remove: []
    remove_regex: []
    remove_modified_configs: false
```

Try to evaluate if you want to merge default values with custom set with an implementation like this:

```
- name: Merge common_pkgs with custom overrides
  set_fact:
    merged_common_pkgs: "{{ common_pkgs | combine(custom_common_pkgs, recursive=True) }}"
```
